* Almacen de las más recientes versiones de los paquetes de R del lab

En este repositorio se almacenan las versiones más recientes de los
paquetes computacionales del [[https://biometriaforestal.uchile.cl][Laboratorio de Biometría y Modelación Forestal]], a cargo  del Profesor [[https://eljatib.com][Christian Salas-Eljatib]]  de la [[https://uchile.cl][Universidad de Chile]].
Los paquetes a los cuales se hace mención se pueden ejecutar
en el software [[https://cran.r-project.org][R]].

En específico los paquetes son  [[https://cran.r-project.org/package=datana][datana]] y  [[https://cran.r-project.org/package=biometrics][biometrics]]. Aunque estos se encuentran disponibles en el repositorio *CRAN* del software R, en
su actualización es algo más lenta de lo que vamos desarrollando por lo cual
es preferible Ud. siempre verifique las versiones de los paquetes instalados.

Los archivos instaladores de =datana= y =biometrics= tienen formato tar.gz, y
además en la carpeta
*manuales* se mantienen los documentos de uso del paquete en cuestón.

Luego de instalado un paquete, 
 Ud. puede proceder como sigue para verificar si quedo correctamente
 instalado.
 # para lo cual se asume que ya tiene instalados los paquetes =biometrics= y =datana= en su versión de R. 

  
Llamarlos a la sesión:

  #+begin_src R
  library(biometrics)
  library(datana)
  #+end_src
y para verificar la versión del paquete, puede emplear la función =packageVersion()= como sigue
#+begin_src R
packageVersion("biometrics")
#+end_src

Cita del paquete
#+begin_src R
citation("biometrics")
#+end_src

** Sugerencias/errores
En caso de encontrar errores, tenga sugerencias, o dudas, por favor escribir a [[mailto:christian.salas@uchile.cl][este email]].

